title = "Alena Tskhondiya"
baseURL = "https://alenatskh.github.io/AlenaTskhondiya_Portfolio/"
languageCode = "en-us"
theme = "ananke"
#themesDir = "../.."

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = "Hi! My name is Alena Tskhondiya"
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/AlenaTskh"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/alena-tskhondiya/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
